### ISSUE TITLE
package on pypi

### ISSUE THREAD

**Issue by stefanfoulis** [fabioz/mu-repo#12]
I want to ``pip install mu`` :-)

**Comment by fabioz** [comment]
Good idea... I'll take a look at that -- although I can't give you an exact date... pull requests welcome too :)

**Comment by hindman** [comment]
Yes, this is a good idea. Even adding a minimal `setup.py` file would help. Here's a start on it:

    import os
    from distutils.core import setup

    setup(
        name        = 'mu_repo',
        version     = '1.0',           # ???
        description = 'Tool to work with multiple git repositories',
        author      = 'Fabio Zadrozny',
        url         = 'https://github.com/fabioz/mu-repo',
        scripts     = ['mu'],
        packages    = ['mu_repo'],
    )

Using that file, I was able to install `mu` on my system like this:

    pip install .

Looking forward to trying out this tool. Thanks for working on it!

**Comment by fabioz** [comment]
Ok, mu-repo is on pip already :)

See: http://fabioz.github.io/mu-repo/install/ for install details (mostly pip install mu-repo now).
