### ISSUE TITLE
mu clone

### ISSUE THREAD

**Issue by chrismcv** [fabioz/mu-repo#15]
It'd be really nice if I could do
```
mu clone <repo> <folder>
```

and it cloned and registered each repo.  And then after checking out a repo with a .mu-repo

```
mu clone
```
which would pull all repos down.

**Comment by fabioz** [comment]
I agree, seems like a nice feature checking out many repos from a .mu_repo file ;)

**Comment by fabioz** [comment]
Ok, I've created a workflow which allows mu-repo to deal with cloning multiple repositories at once. See: http://fabioz.github.io/mu-repo/cloning/ for details.

**Comment by chrismcv** [comment]
awesome! thanks :)
