### ISSUE TITLE
De-colorize output from git when color.ui is "always"

### ISSUE THREAD

**Issue by teolisitza** [fabioz/mu-repo#19]
mu checkout master failed for me with the following:

>  cl-tools : git checkout master
>    error: pathspec '"\033[32mmaster\033[m"' did not match any file(s) known to git.

until I turned color.ui to "auto". This is more of a tip since the workaround is the default behavior, thanks for the cool code!

**Comment by fabioz** [comment]
Closing since there are no plans to implement this -- pull requests welcome ;)
