### ISSUE TITLE
mu not working after recent commit - all repos give me a usage message as if my arguments were wrong

### ISSUE THREAD

**Issue by jpwgarrison** [fabioz/mu-repo#21]
Symptom is all repos give me a usage message as if my arguments were wrong:

```
 mu-repo : git status
    usage: git [--version] [--help] [-C <path>] [-c name=value]
    [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
    [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
    [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
    <command> [<args>]
```

I reverted to commit d9f8bf3e1a391cc40b7c6e8df2db7eaef69803ca and everything works.

**Comment by fabioz** [comment]
Humm, can you get the latest master, just revert the commit https://github.com/fabioz/mu-repo/commit/9922603f9e0a5b4e02c412292e3a0b186e2a3a5b and see if it works (it should mostly remove the shell=True parameter passed for Popen).

**Comment by jpwgarrison** [comment]
```
$ git revert 9922603
```

Does fix the issue, thanks for looking.

**Comment by jpwgarrison** [comment]
So I should probably specify ubuntu 14.04, git version 1.9.1

**Comment by fabioz** [comment]
Ok, the latest master should now be working for you.

**Comment by jpwgarrison** [comment]
Confirmed, thanks!
