### ISSUE TITLE
Register all failed silently on OSX

### ISSUE THREAD

**Issue by cbaggers** [fabioz/mu-repo#26]
Neither `mu register --all` or `--recursive` seemed to work on OSX. Both gave me empty results for `mu list`.

I didnt see any errors and so instead just used `ls -d */ | xargs -I {} mu register {}` instead. 

`mu` itself seems to be working great though! Thanks so much for making it

**Comment by fabioz** [comment]
I just tested running `mu register --all` on mac os and it seems to work fine for me, so, I need more information on how to reproduce this.

The code is actually pretty simple/straightforward: https://github.com/fabioz/mu-repo/blob/master/mu_repo/action_register.py, so, if you're inclined you can take a look there on your actual use case to know what could go wrong (i.e.: `mu register --all` just searches for `.git` directories in subfolders and if a match is found it adds it to `.mu_repo`).

**Comment by cbaggers** [comment]
Thanks for checking that. I think this was my mistake in that I tried to register all the subdirectories, however the directory I was in was a repo itself and the subdirectories were submodules. I'm closing this one. 
Thanks again.
