### ISSUE TITLE
repositories with .git FILE are ignored

### ISSUE THREAD

**Issue by imposeren** [fabioz/mu-repo#30]
I have a lot repositories with .git file that has content like:

```
gitdir: /home/user/foo/bar/repo1
```

When trying to run `mu register --all` mu-repo does not treat such directories as a git repository

**Comment by fabioz** [comment]
Can you explain how to reproduce a bit better? (i.e.: describe better the directory structure and where in that structure you're running `mu register --all` and it doesn't work, so that it's possible to do a reproducible test case).

**Comment by fabioz** [comment]
Closing as there was no further comments.
