### ISSUE TITLE
branch names "guessing" is not working

### ISSUE THREAD

**Issue by igortg** [fabioz/mu-repo#35]
*mu checkout* used to work even with partial branch names.

In the current version, if the user doesn't give the branch full name, the following exception occurs:
```
  File "W:\Miniconda\lib\site-packages\mu_repo\action_checkout.py", line 27, in Run
    branch, _repo = iteritems(branch_to_repos).next()
AttributeError: 'dict_items' object has no attribute 'next'
```

**Comment by fabioz** [comment]
Yeap, it seems it was only working on Python 2, thanks for the patch ;)
