### ISSUE TITLE
Allow remotes other than 'origin'

### ISSUE THREAD

**Issue by jbrwilkinson** [fabioz/mu-repo#41]
When working with more than one remote, it's useful to name the remote according to e.g. the service it came from:

    git clone --origin github https://jbwilkinson@github.com/fabioz/mu-repo

or

    git clone --origin home-nas git://home-nas/mu-repo

etc

`mu-repo` currently assumes that a remote is named 'origin'. When it isn't, many commands fail.

**Comment by fabioz** [comment]
Seems reasonable (there are really a few hard-coded `origin` occurrences: https://github.com/fabioz/mu-repo/search?q=origin&unscoped_q=origin).

Note: from what I could see, the commands which would fail are the custom ones such as: `mu acp`, `mu p`, `mu rb`, 'mu up`, `mu upd`.

If there's only one remote, it should probably query to make sure it's using the one available, but if there's more than one it could get the default from an env var or specify in the command line.. maybe something as `mu rb --remote=<remote-name>`.

What do you think? Any suggestions?

**Comment by fabioz** [comment]
Closing since there are no plans to implement this -- pull requests welcome ;)
