### ISSUE TITLE
Feature: Add targeting for groups in regular commands

### ISSUE THREAD

**Issue by LordMike** [fabioz/mu-repo#44]
So f.ex. today, we can do: `mu st repo:repo1,repo2`.. But we cannot add `repo1, repo2` to a group `x`, and then do `mu st repo:x`.

I suggest that the `repo:` filter should first check for repositories by name, and if they don't exist, check for groups of the same name. If not already the case, groups should not be allowed to be named the same as repositories.

This will also allow me to do: `mu st repo:x,other-repo` to target `repo1, repo2 and other-repo`.

**Comment by fabioz** [comment]
Would you be interested in providing a pull request for this? 

Should be straightforward -- adding this would probably touch https://github.com/fabioz/mu-repo/blob/master/mu_repo/__init__.py#L146 and  https://github.com/fabioz/mu-repo/blob/master/mu_repo/__init__.py#L211

**Comment by fabioz** [comment]
Actually, as I wanted to add that for some time and it was very straightforward, I'll add this (just created a pull request -- https://github.com/fabioz/mu-repo/pull/46 -- so, should land soon).

It also lets you specify the repo/group with `@` or `#` -- i.e.: `mu st @repo1,repo2,group1`

**Comment by LordMike** [comment]
#46 has been closed.
