### ISSUE TITLE
Feature: Add targeting for groups in regular commands

### ISSUE THREAD

**Issue by LordMike** [fabioz/mu-repo#45]
So f.ex. today, we can do: `mu st repo:repo1,repo2`.. But we cannot add `repo1, repo2` to a group `x`, and then do `mu st repo:x`.

I suggest that the `repo:` filter should first check for repositories by name, and if they don't exist, check for groups of the same name. If not already the case, groups should not be allowed to be named the same as repositories.

This will also allow me to do: `mu st repo:x,other-repo` to target `repo1, repo2 and other-repo`.

Note: Github is having issues today, so I may have double-posted this as #44. If that's the case, close this one.

**Comment by fabioz** [comment]
Yeap, GitHub seems to be having issues today... closing this one.
