### ISSUE TITLE
Feature: Add detection for redirects

### ISSUE THREAD

**Issue by LordMike** [fabioz/mu-repo#48]
Cloning using `mu`, against Gitlab, will work for `https://xyz.com/Group/Repo`, but will break future `mu` features like grouping, because Gitlab redirects to `https://xyz.com/Group/Repo.git/`.

I mentioned this in #42, but didn't create an issue on it. The issue is that for Gitlab.com, you can use both a non `.git` address, and a `.git` address to clone/work with, with Gitlab redirecting you to the `.git` version always.

This shows up in git cli with a `warning: redirecting to https://xyz.com/Group/Repo.git/`. The solution is to not have a redirect, as in cloning with the `.git/` end. It will directly affect `mu`, in that all `mu` actions (`st`, `up` etc.), in that `mu` can't group the results.

I don't know how to fix this. I can think of the following:

* Have git not follow redirects (somehow), detect the error and report back, let the user fix the link
* Configure git (somehow) to store the redirected address
* Perform an HTTP call (when the git address is HTTP/S) to `REPO/info/refs`, and follow any redirect till the end. Then use the final address as a cloning url.
* Ignore that specific warning, so that `mu` can group correctly again

**Comment by fabioz** [comment]
Closing since there are no plans to implement this -- pull requests welcome ;)
