### ISSUE TITLE
Checkout a branch where name is composed by another one

### ISSUE THREAD

**Issue by lincrosenbach** [fabioz/mu-repo#52]
When locally someone has a branch like rb-rfdap_workbench-v0.10.1 and a checkout is wanted on rb-rfdap_workbench-v0.10, then the following error occurs. There is a workaround which is to delete locally the branch which has the other name in composition.

rfdap → mu branch

  . : git branch
    master
    rb-rfdap_workbench-v0.10.1

rfdap → mu co rb-rfdap_workbench-v0.10

  File "/home/rosenbach/Work/miniconda/lib/python3.6/site-packages/mu_repo/action_checkout.py", line 27, in Run
    branch, _repo = iteritems(branch_to_repos).next()
AttributeError: 'dict_items' object has no attribute 'next'

**Comment by fabioz** [comment]
Your version is outdated (this was already fixed), so, please update ;)
