### ISSUE TITLE
Problem using mu repo with git credential manager for Windows

### ISSUE THREAD

**Issue by ep1428** [fabioz/mu-repo#53]
Hi,

I have a problem when using mu repo together with git credential manager for Windows. 
When I do 'mu fetch' i get spammed with credential manager windows. 

Does anyone have a solution/work-around for my problem or is this a dead end?

**Comment by fabioz** [comment]
I must say I don't know (I always use `plink`/`pageant` on windows and it seems to work without any issues for me).

Anyways, this doesn't seem fixable in mu repo as it just calls `git` multiple times -- i.e.: showing multiple credential manager windows is not an issue with mu repo.
