### ISSUE TITLE
Shortcut conflicts with shortcut in my .gitconfig

### ISSUE THREAD

**Issue by ghost** [fabioz/mu-repo#57]
the `mu p` shortcut conflicts with a shortcut that exists in my git config. Thus, running `mu p` takes a different action than `git p`. That is unexpected behavior and quite jarring.

I think overriding user-set configuration from git is not appropriate when you explicitly support the behavior.

Is it possible to set a config to first honor git config shortcuts before using the mu shortcuts?

**Comment by fabioz** [comment]
I agree that if you have such an alias it should be respected, while it should also work with its own aliases.

The place where this happens is at https://github.com/fabioz/mu-repo/blob/master/mu_repo/__init__.py#L245

While I don't currently have time/plans to implement this, I'm open to pull requests with a fix here -- an option could be adding the aliases that should not be ignored to the `.mu_repo` config file.

-- the workaround is locally deleting that line or using `mu sh` to call git with your alias (something as `mu sh git p`).

**Comment by fabioz** [comment]
Closing since there are no plans to implement this (pull requests still welcome).
