### ISSUE TITLE
mu group cloning all repo's in a group

### ISSUE THREAD

**Issue by honeybajaj** [fabioz/mu-repo#62]
I am not able to find a way to clone all repo's in a group, created multiple groups and register repo's but can't seem to clone them. Can you kindly suggest how I can clone all repo's in a group.

**Comment by fabioz** [comment]
Have you followed the instructions at: https://fabioz.github.io/mu-repo/cloning/ ?

Note that you need to upload the `.mu_repo` file to the repository for it to work.

**Comment by fabioz** [comment]
Closing since no further info was given.
