### ISSUE TITLE
Could  command "mu clone -all"  support parameters like "-b branch --single-branch".

### ISSUE THREAD

**Issue by Ivan-ma** [fabioz/mu-repo#63]
Since our git repositories are big, I would like to use git shallow-clone to only clone one branch(refer to [link](https://www.atlassian.com/git/tutorials/big-repositories)) to save my disk space.

I want to clone all repositories in the group, by using command like this:
`mu clone -all -b release/1.21 --single-branch`

Could it be supported?

**Comment by fabioz** [comment]
It could probably be supported, yes, still, it's not something I'll probably use, so, I won't be implementing this myself, but pull requests are welcome.

**Comment by fabioz** [comment]
Closing since there are no plans to implement it (pull requests still welcome).
