### ISSUE TITLE
To support short name for a repo

### ISSUE THREAD

**Issue by jiming** [fabioz/mu-repo#65]
Hi Dude,

Many thanks for the great tool!

Some time, the repo is in deep directory and I wanted to maintian the .mu_repo globally.
```
repo=/mnt/d/projects/working/someapp/RCN-918/app-config
```
This absolute path is too long to be put in group config

Is it possible to support a short name for the repo as follows:

```
repo=/mnt/d/projects/working/someapp/RCN-918/app-config, someapp-app-conf
```

So I can use someapp-app-conf in group config

Have a nice day!

**Comment by fabioz** [comment]
Hello @jiming. I don't have anything against that, but I'm probably not going to implement that myself as I don't really have that need.

So, if you're willing to provide a pull request, I can take a look at it ;)

**Comment by jiming** [comment]
Ok, thank you! It's a pitty that I am not able to write python.

Thanks anyway and have a nice day!
