### ISSUE TITLE
Multiple repos and authentication

### ISSUE THREAD

**Issue by stessaris** [fabioz/mu-repo#67]
When I `pull` from multiple repos `git` complains that cannot authenticate on one of them; but restricting the operation only on that repository using `repo:` is not reporting any error (see screenshot below). I don't understand what's the difference.

I'm using mu 1.8.1

<img width="100%" alt="Screenshot" src="https://user-images.githubusercontent.com/39191293/152778097-f8e138f4-8e53-4c00-97c1-8ab7fa889789.png">

**Comment by fabioz** [comment]
I'm not exactly sure why that happens either... One thing that is different may be whether commands are run in parallel or not.

If you force it to run serially does this also happen?

i.e.: Set an environment variable: `MU_REPO_SERIAL=True` in your terminal and retry.

The difference is that in serial mode `stderr` and `stdout` are not piped -- which could make a difference here.

Related code: https://github.com/fabioz/mu-repo/blob/a452d44c66c51224cceab502c949448ba26b444d/mu_repo/execute_git_command_in_thread.py#L90
