### ISSUE TITLE
Enable a "silent mode" to suppress mu-specific command output.

### ISSUE THREAD

**Issue by mlamb24** [fabioz/mu-repo#68]
When running a command like `mu status --porcelain` or a more low-level equivalent for checking for changes such as `mu diff-index HEAD --`, the output for each command being run makes it inconvenient to use the output of these commands conveniently.  Can a parameter or toggle be added to use mu "quietly" so that commands can more easily be run where the mu-specific output is not needed or where the only thing we care about is that there is output, not which repo it comes from?

**Comment by fabioz** [comment]
It could probably be supported, yes, still, it's not something I'll probably use, so, I won't be implementing this myself, but pull requests are welcome.

**Comment by mlamb24** [comment]
@fabioz Do you know if there is a single point where those commands are printed off the top of your head before I go digging?  If it's simple I will definitely put in a request!  Thanks either way!

**Comment by fabioz** [comment]
I believe that what you want suppressed is: https://github.com/fabioz/mu-repo/blob/master/mu_repo/execute_git_command_in_thread.py#L87

**Comment by mlamb24** [comment]
Great!  Thank you!

**Comment by fabioz** [comment]
Closing (pull requests still welcome, but I see no point in leaving the issue lingering open in the tracker since there aren't any plans to tackle this anyways).
