### ISSUE TITLE
Provide a better option to run non-git commands (mu sh command and create aliases).

### ISSUE THREAD

**Issue by KeithTsui** [fabioz/mu-repo#7]
Hi,

If I wanted to run some commands to build the repos like "mvn clean install", how would I do it with this tool?

-Keith

**Comment by raine** [comment]
I think there should be a better way to do this.

**Comment by fabioz** [comment]
@raine do you have some proposal on that?

**Comment by raine** [comment]
Perhaps something like `mu sh 'ls -1 | head -1'`?

**Comment by nicoddemus** [comment]
`mu sh 'ls -1'` would break backward compatibility and the intended usage for `mu`, which is to execute **git** commands. In your proposal there's now way for `mu` to distinguish if the user meant to execute `git X Y` or just `X Y` when typing `mu X Y`.

How about adding a flag then? `mu -e 'sh ls -l1 | head -1'`?

**Comment by raine** [comment]
Can you elaborate? `mu list` is not a git command yet it exists.

**Comment by nicoddemus** [comment]
Apparently it was decided to include some "builtin" commands besides Git's.

**Comment by fabioz** [comment]
I think a flag vs a command to execute something is almost the same... the only thing is that it must not conflict with some git command (i.e.: both `mu sh` and `mu -e` work as long as git itself doesn't have something which conflicts... if we make `sh` the specification of the custom command to execute something).

Currently mu-repo has things as commands and not flags, so, `mu sh` would be closer to what's available right now, although I'm still not sure if I like `mu sh` or `mu -e` better... thoughts?

p.s.: With this addition, it might be worth having something as aliases in mu later on (so, you could register a `mu sh ls -1 | head -1` with a `mu ls` alias).

I like the idea... ;)

**Comment by raine** [comment]
I vote for `mu sh ls`. It seems like the most intuitive option to me.

**Comment by nicoddemus** [comment]
Oh I thought `sh` was being used just as an example, as in `mu wget`, `mu conda` etc... but now I see that what was suggested was actually `mu sh conda`, `mu sh wget`, etc. 

Completely agree that `mu sh` is the most intuitive option. :smile:

**Comment by fabioz** [comment]
Ok, agreed with `mu sh` then ;)

@raine, would you be interested in providing a pull request for that?

**Comment by raine** [comment]
I'm afraid I don't have time to learn python right now.

**Comment by fabioz** [comment]
Ok, well, I'm not sure when I'll be able to get it either, so, for now I'm just reopening the issue ;)

**Comment by fabioz** [comment]
Ok, just implemented this. Will be available for 1.6.0 (or if installed from the repo, just update it).
