### ISSUE TITLE
Feature: repository filtering

### ISSUE THREAD

**Issue by rocketraman** [fabioz/mu-repo#73]
It would be nice if the set of repositories could be filtered based on some dynamic properties. For example:

* only operate on repositories that have a dirty status
* only operate on repositories in which a branch exists
* only operate on repositories where a passed shell command returns a 0 exit status
* etc.

It would be a kind of dynamic grouping function.

**Comment by fabioz** [comment]
Hi @rocketraman.

To be fair, I don't really see this being implemented by myself (I don't see that much value and haven't really missed that feature). Are you interested in providing a PR?

**Comment by rocketraman** [comment]
@fabioz Thanks for your reply. Maybe I'm just missing the right way to use the tool. How do you handle the case where a branch is in a subset of the repos, and you want to run commands only on repos with that branch name? Or do you just create the branch in every repo, and sometimes it just remains a pointer to `master`?

**Comment by rocketraman** [comment]
Thanks, let me try that approach. My issue for the change I am working on now is I don't know which repositories I'll be changing in advance, so the group is more "dynamic". However, I can see that appproach working for the majority of use cases.

I don't have time to submit a PR at the moment, so I'll go ahead and close this.

**Comment by fabioz** [comment]
As a note, the `.mu_repo` file format is pretty simple, so, sometimes it's easy to just edit in an editor to define what you're working with (or to change groups).
