### ISSUE TITLE
Feature: new command to switch to common branches

### ISSUE THREAD

**Issue by nicoddemus** [fabioz/mu-repo#8]
A new command named `switch` that lists branches common to all registered repositories and lets him to switch all at the same time.

The branches would be indexed, allowing the user to just type the index instead of having to type a full branch name. For example:

```
]mu switch 
Common branches:
[1] fb-SSRL-2.9
[2] master
[3] stable-12.0-master

Switch to which branch? 1
```

In the example above, the user selected `1` which in turn checked out branch `fb-SSRL-2.9` for all registered repositories.

Also, an option `--all` should be added to also list common remote branches besides local ones.

**Comment by fabioz** [comment]
Note that I implemented the suggestion by campos for partial matches (although the initial issue is still valid, so, keeping it open).

**Comment by fabioz** [comment]
Closing since there are no plans to implement this -- pull requests welcome ;)
